# Generated by Django 5.0.4 on 2024-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
